api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'docs', views.DocumentListViewSet)


# Wire up our API using automatic URL routing.

urlpatterns = [
    url(r'^', include(router.urls)),
    #url(r'^(?P<document_id>pdfs/\w+\.pdf)/$', views.pdf_view_api, name='pdf_view_api'),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

myjangostartup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^',include('upload.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'upload/login.html'}, name='login'),
    url(r'^dictionary/',include('dictionary.urls')),
    url(r'^api/', include('api.urls', namespace='rest_framework')),
]

upload/urls.py
from django.conf.urls import url

from . import views

app_name = 'upload'
urlpatterns = [
    # ex: /upload/
    url(r'^$', views.UploadView.as_view(), name='index'),
    # ex: /upload/done/
    url(r'^done/$', views.done, name='done'),
    url(r'^reindex/$', views.reindex_files, name='reindex'),
    url(r'^(?P<document_id>attachments/\w+\.pdf)/$', views.pdf_view, name='view'),
    url(r'^logout/$', views.logout_user, name='logout'),
]

upload/models.py
from django.db import models
from django.utils import timezone

from dictionary.models import MedicalTerm, DocumentType, BloodType
from django.contrib.auth.models import User
from django.urls import reverse

# test p12345678


class Document(models.Model):
    file_attached = models.FileField(upload_to='attachments')
    all_content = models.TextField()
    visit_date = models.DateField(default=timezone.now())
    tags = models.ManyToManyField(MedicalTerm)
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True)
    doc_type = models.ForeignKey(DocumentType,
                                 on_delete=models.CASCADE,
                                 default=DocumentType.COMMON_RECIPE)

    def get_absolute_url(self):
        return reverse('upload.pdf_view', args=[self.file_attached])

    class Meta:
        ordering = ['user', 'visit_date']

    def __str__(self):
        tags = ' '.join(sorted(['['+x.name+']' for x in self.tags.all()])[:20])
        if not tags:
            tags = u'Cannot recognize text'
        description = tags if self.file_attached else u'File not loaded'
        return u'%s : %s' % (str(self.visit_date), description)


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    birth_date = models.DateField(default='1900/01/01')
    blood_type = models.ForeignKey(BloodType, default=0)

    def __str__(self):
        return u'%s, born %s, blood: %s, %d documents' % (
            self.name,
            str(self.birth_date),
            self.blood_type,
            0
        )

upload/forms.py
# forms.py
from django import forms
from multiupload.fields import MultiFileField

class UploadForm(forms.Form):
    attachments = MultiFileField(min_num=1, max_num=10, max_file_size=1024*1024*5)
'''
    # If you need to upload media files, you can use this:
    attachments = MultiMediaField(
        min_num=1, 
        max_num=3, 
        max_file_size=1024*1024*5, 
        media_type='video'  # 'audio', 'video' or 'image'
    )

    # For images (requires Pillow for validation):
    attachments = MultiImageField(min_num=1, max_num=3, max_file_size=1024*1024*5)
'''

upload/views.py
from django.views.generic.edit import FormView
from .forms import UploadForm
from .models import Document
from dictionary.models import MedicalTerm
from django.shortcuts import render
from django.urls import reverse

from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout

from .ocr import OcrThread
from .analyze import AnalyzeThread

from django.http import FileResponse

pending_pdfs_list = []


@login_required
def done(request):
    l = pending_pdfs_list[:]
    print('list!' + str(l))
    ocrThread = OcrThread(pending_pdfs_list)
    ocrThread.start()

    template_name = 'upload/done.html'
    initial = {'file_list_string': ','.join(l)}
    return render(request, template_name, initial)


@login_required
def pdf_view(request, document_id):
    return FileResponse(open(document_id, 'rb'), content_type='application/pdf')


@login_required
def reindex_files(request):
    analyzeThread = AnalyzeThread('')
    analyzeThread.start()
    return HttpResponseRedirect(reverse('upload:index'))


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('upload:index'))


class UploadView(LoginRequiredMixin, FormView):
    template_name = 'upload/form.html'
    form_class = UploadForm
    success_url = 'done/'


    def get(self, request, *args, **kwargs):
        self.request = request
        query = Document.objects.filter(user=request.user)
        if request.GET.get("filters"):
            names = request.GET["filters"].split(',')
            filters = MedicalTerm.objectsByNames(names)
            for f in filters:
                query = query.filter(tags=f)

        docs = query.order_by('-visit_date')[:20]
        request_dict = {'form': self.form_class, 'document_list': docs}
        return render(request, self.template_name, request_dict)

    def form_valid(self, form):
        for each in form.cleaned_data['attachments']:
            file_path = 'attachments/' + each.name
            # if no documents with this name
            o = Document.objects
            if (not o.filter(file_attached=file_path)):
                o.create(file_attached=each, user=self.request.user)
                pending_pdfs_list.append(file_path)
            else:
                print(file_path + ' exists!')

        return super(UploadView, self).form_valid(form)

upload/templates/upload/done.html
<h2>{{"Done!"}}</h2>
{% if file_list_string %}
    <p>{{ file_list_string }} are uploaded and about to be processed.</p>
{% else %}
    <p>No new files uploaded</p>
{% endif %}
<br>
<form action="{% url 'upload:index' %}">
    <input type="submit" value="Return to index"/>
</form>

upload/templates/upload/form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send" />
</form>
<br><hr><br>
<form action = "" method="get">
  <input type="text" name="filters" value = {{ request.GET.filters }}>
    <input type="submit" value="Filter by tags">
</form>
{% if document_list %}
    <ul>
    {% for doc in document_list %}
        {% if doc.file_attached %}
            <li><a href="{% url 'upload:view' doc.file_attached %}">{{ doc }}</a></li>
        {% else %}
            <li>{{doc}}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No documents are available.</p>
{% endif %}
<hr>
<form action="{% url 'upload:logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Logout">
</form>

upload/templates/upload/login.html
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}